import { Categoria, Producto } from "./types";

const img = (nombre: string) => `/productos/${nombre}`;

export const categorias: Categoria[] = [
  { id: "entradas", nombre: "Entradas", orden: 1 },
  { id: "porciones", nombre: "Porciones", orden: 2 },
  { id: "arroz-personal", nombre: "Arroz Personal", orden: 3 },
  { id: "arroz-2", nombre: "Arroz x2", orden: 4 },
  { id: "arroz-3", nombre: "Arroz x3", orden: 5 },
  { id: "familiar-4", nombre: "Familiar x4", orden: 6 },
  { id: "familiar-6", nombre: "Familiar x6", orden: 7 },
  { id: "especiales", nombre: "Especiales", orden: 8 },
  { id: "a-la-carta", nombre: "A la Carta", orden: 9 },
  { id: "comida-rapida", nombre: "Comida Rápida", orden: 10 },
  { id: "bebidas", nombre: "Bebidas", orden: 11 },
];

export const productos: Producto[] = [
  // ---------- ENTRADAS ----------
  {
    id: "ent-lumpias",
    categoriaId: "entradas",
    nombre: "Lumpias",
    descripcion: "Rollo frito con exquisito interior de pollo, jamón y vegetales.",
    precio: 3800,
    imagen: img("lumpias.jpg"),
    activo: true,
  },
  {
    id: "ent-aros",
    categoriaId: "entradas",
    nombre: "Aros de Cebolla",
    descripcion: "Exquisitos aros de cebolla crujientes. Porción x8 unidades.",
    precio: 12000,
    imagen: img("aros-cebolla.jpg"),
    activo: true,
  },
  {
    id: "ent-wonton",
    categoriaId: "entradas",
    nombre: "Wonton Frito",
    descripcion: "Bocados crujientes de cerdo fusionados con especias chinas. Porción x7 unidades.",
    precio: 13000,
    imagen: img("wonton.jpg"),
    activo: true,
  },
  {
    id: "ent-camarones",
    categoriaId: "entradas",
    nombre: "Camarones O.K.",
    descripcion: "120 gr de camarón salteado en soya y aceite de sésamo con raíz y cebollino.",
    precio: 15000,
    imagen: img("camarones.jpg"),
    etiquetas: ["Picante"],
    destacado: true,
    activo: true,
  },

  // ---------- PORCIONES (sin foto, formato lista como en la carta física) ----------
  {
    id: "por-papa-240",
    categoriaId: "porciones",
    nombre: "Papa Francesa x240 gr",
    descripcion: "Porción individual.",
    precio: 7500,
    activo: true,
  },
  {
    id: "por-papa-360",
    categoriaId: "porciones",
    nombre: "Papa Francesa x360 gr",
    descripcion: "Porción grande para compartir.",
    precio: 11000,
    activo: true,
  },
  {
    id: "por-costillas",
    categoriaId: "porciones",
    nombre: "Costillas de Cerdo x250 gr",
    descripcion: "Incluye papas a la francesa x120 gr.",
    precio: 16500,
    activo: true,
  },
  {
    id: "por-alitas",
    categoriaId: "porciones",
    nombre: "Alitas con BBQ",
    descripcion: "4 alas + papas a la francesa x120 gr.",
    precio: 13500,
    activo: true,
  },
  {
    id: "por-huevos",
    categoriaId: "porciones",
    nombre: "Huevos de Codorniz",
    descripcion: "Porción x5 unidades.",
    precio: 4000,
    activo: true,
  },
  {
    id: "por-palillos",
    categoriaId: "porciones",
    nombre: "Palillos Chinos",
    descripcion: "Sachet x2 palillos.",
    precio: 2000,
    activo: true,
  },
  {
    id: "por-cuarto-pollo",
    categoriaId: "porciones",
    nombre: "1/4 de Pollo Frito",
    descripcion: "1 pierna pernil + papas x60 gr.",
    precio: 13000,
    activo: true,
  },
  {
    id: "por-medio-pollo",
    categoriaId: "porciones",
    nombre: "1/2 Pollo Frito",
    descripcion: "2 piernas pernil + papas x120 gr.",
    precio: 20000,
    activo: true,
  },
  {
    id: "por-pollo-entero",
    categoriaId: "porciones",
    nombre: "1 Pollo Frito",
    descripcion: "4 piernas pernil + papas x240 gr.",
    precio: 33000,
    activo: true,
  },

  // ---------- ARROZ CHINO PERSONAL ----------
  {
    id: "arroz-personal",
    categoriaId: "arroz-personal",
    nombre: "Arroz Chino Personal",
    descripcion: "Arroz chino 350 gr + pollo desmenuzado + carne picada + jamón + vegetales + papas x60 gr + 1 huevo de codorniz.",
    precio: 11000,
    imagen: img("arroz-personal.jpg"),
    masVendido: true,
    activo: true,
    variantes: [
      { id: "solo", nombre: "Solo", precio: 11000 },
      { id: "vegetariano", nombre: "Vegetariano", precio: 12000, descripcion: "Zuchchini, brócoli, apio, pimentón, raíz, zanahoria, maíz y cebollino." },
      { id: "lomo", nombre: "+ Lomo de Cerdo", precio: 15500 },
      { id: "pechuga", nombre: "+ Pechuga", precio: 15500 },
      { id: "cuarto-pollo", nombre: "+ 1/4 de Pollo (pierna pernil)", precio: 18000 },
      { id: "alitas", nombre: "+ 3 Alitas con BBQ", precio: 18000 },
      { id: "costilla", nombre: "+ Costilla de Cerdo 130 gr", precio: 18000 },
      { id: "camaron", nombre: "+ Camarón y Palmitos", precio: 18000 },
    ],
  },

  // ---------- ARROZ CHINO 2 PERSONAS ----------
  {
    id: "arroz-2",
    categoriaId: "arroz-2",
    nombre: "Arroz Chino para 2",
    descripcion: "Arroz chino 700 gr + pollo desmenuzado + carne picada + jamón + vegetales + papas x120 gr + 2 huevos de codorniz.",
    precio: 20000,
    imagen: img("arroz-dos.jpg"),
    destacado: true,
    activo: true,
    variantes: [
      { id: "solo", nombre: "Solo", precio: 20000 },
      { id: "lomo", nombre: "+ Lomo de Cerdo (2 porciones)", precio: 27000 },
      { id: "pechuga", nombre: "+ Pechuga (2 porciones)", precio: 27000 },
      { id: "cuarto-pollo", nombre: "+ 1/4 de Pollo (pierna + alita)", precio: 29000 },
      { id: "alitas", nombre: "+ 4 Alitas con BBQ", precio: 29000 },
      { id: "costilla", nombre: "+ Costilla de Cerdo 250 gr", precio: 29000 },
      { id: "camaron", nombre: "+ Camarón y Palmitos", precio: 29000 },
    ],
  },

  // ---------- ARROZ CHINO 3 PERSONAS ----------
  {
    id: "arroz-3",
    categoriaId: "arroz-3",
    nombre: "Arroz Chino para 3",
    descripcion: "Arroz chino 1050 gr + pollo desmenuzado + carne picada + jamón + vegetales + papas x180 gr + 3 huevos de codorniz. Se vende únicamente con adición, elige una:",
    precio: 32000,
    imagen: img("arroz-tres.jpg"),
    activo: true,
    variantes: [
      { id: "lomo", nombre: "+ Lomo de Cerdo (3 porciones)", precio: 32000 },
      { id: "pechuga", nombre: "+ Pechuga (3 porciones)", precio: 32000 },
      { id: "alitas", nombre: "+ 6 Alitas con BBQ", precio: 34000 },
      { id: "costilla", nombre: "+ Costilla de Cerdo 380 gr", precio: 34000 },
      { id: "camaron", nombre: "+ Camarón y Palmitos 160 gr", precio: 34000 },
    ],
  },

  // ---------- FAMILIAR PARA 4 ----------
  {
    id: "fam4-solo",
    categoriaId: "familiar-4",
    nombre: "Arroz Chino Familiar para 4",
    descripcion: "Arroz chino 1400 gr + pollo desmenuzado + carne picada + jamón + vegetales + papas x240 gr + 4 huevos de codorniz.",
    precio: 31000,
    imagen: img("arroz-tres.jpg"),
    activo: true,
  },
  {
    id: "fam4-valenciano",
    categoriaId: "familiar-4",
    nombre: "Valenciano",
    descripcion: "1/2 pollo frito (2 piernas pernil) + arroz chino 1400 gr + pollo desmenuzado, carne picada, jamón, vegetales y papas x240 gr + 4 huevos de codorniz.",
    precio: 39000,
    imagen: img("valenciano.jpg"),
    destacado: true,
    activo: true,
    variantes: [
      { id: "tradicional", nombre: "Valenciano Tradicional", precio: 39000 },
      { id: "camaron", nombre: "Valenciano + Camarón y Palmitos", precio: 46000, descripcion: "Incluye camarones y palmitos x120 gr adicionales." },
    ],
  },
  {
    id: "fam4-especial",
    categoriaId: "familiar-4",
    nombre: "Especial",
    descripcion: "Arroz chino 1400 gr + camarones y palmitos x240 gr + pollo desmenuzado + carne picada + jamón + vegetales + papas x240 gr + 4 huevos de codorniz.",
    precio: 42000,
    imagen: img("especial.jpg"),
    activo: true,
  },
  {
    id: "fam4-super",
    categoriaId: "familiar-4",
    nombre: "Super",
    descripcion: "Costillitas x500 gr + arroz chino 1400 gr + pollo desmenuzado + carne picada + jamón + vegetales + papas x240 gr + 4 huevos de codorniz.",
    precio: 42000,
    imagen: img("super.jpg"),
    activo: true,
  },
  {
    id: "fam4-alitas",
    categoriaId: "familiar-4",
    nombre: "Alitas con BBQ",
    descripcion: "8 alitas con BBQ + arroz chino 1400 gr + pollo desmenuzado + carne picada + jamón + vegetales + papas x240 gr + 4 huevos de codorniz.",
    precio: 42000,
    imagen: img("alitas-x4.jpg"),
    activo: true,
  },
  {
    id: "fam4-ahumadas",
    categoriaId: "familiar-4",
    nombre: "Carnes Ahumadas O.K.",
    descripcion: "Pollo desmenuzado + cerdo picado + res + chorizo y jamón ahumados en un delicioso arroz tradicional con vegetales, papas x240 gr y 4 huevos de codorniz.",
    precio: 42000,
    imagen: img("carnes-ahumadas.jpg"),
    etiquetas: ["Nuevo"],
    activo: true,
  },
  {
    id: "fam4-frutos-mar",
    categoriaId: "familiar-4",
    nombre: "Frutos del Mar",
    descripcion: "Arroz salteado con pescado, calamar, pulpo baby, palmitos de cangrejo, camarones, 4 conchitas, papas x240 gr y 4 huevos de codorniz.",
    precio: 53000,
    imagen: img("frutos-del-mar.jpg"),
    etiquetas: ["Nuevo"],
    activo: true,
  },
  {
    id: "fam4-paisa",
    categoriaId: "familiar-4",
    nombre: "Super Paisa",
    descripcion: "Arroz con vegetales, plátano dulce, maíz tierno, chorizo, pollo desmenuzado, cerdo picado, trocitos de costilla ahumada, chicharroncitos, jamón, papas x240 gr y 4 huevos de codorniz.",
    precio: 54000,
    imagen: img("arroz-paisa.jpg"),
    masVendido: true,
    activo: true,
  },

  // ---------- FAMILIAR PARA 6 ----------
  {
    id: "fam6-solo",
    categoriaId: "familiar-6",
    nombre: "Arroz Chino Familiar para 6",
    descripcion: "Arroz chino 2100 gr + pollo desmenuzado + carne picada + jamón + vegetales + papas x360 gr + 6 huevos de codorniz.",
    precio: 50000,
    imagen: img("arroz-dos.jpg"),
    activo: true,
  },
  {
    id: "fam6-valenciano",
    categoriaId: "familiar-6",
    nombre: "Valenciano",
    descripcion: "3/4 pollo frito (3 piernas pernil) + arroz chino 2100 gr + pollo desmenuzado, carne picada, jamón, vegetales y papas x360 gr + 6 huevos de codorniz.",
    precio: 65000,
    imagen: img("valenciano.jpg"),
    activo: true,
    variantes: [
      { id: "tradicional", nombre: "Valenciano Tradicional", precio: 65000 },
      { id: "camaron", nombre: "Valenciano + Camarón y Palmitos", precio: 79000, descripcion: "Incluye camarones y palmitos x160 gr adicionales." },
    ],
  },
  {
    id: "fam6-super",
    categoriaId: "familiar-6",
    nombre: "Super",
    descripcion: "Costillitas x750 gr + arroz chino 2100 gr + pollo desmenuzado + carne picada + jamón + vegetales + papas x360 gr + 6 huevos de codorniz.",
    precio: 70000,
    imagen: img("super.jpg"),
    activo: true,
    variantes: [
      { id: "solo", nombre: "Super", precio: 70000 },
      { id: "camaron", nombre: "Super + Camarón y Palmitos", precio: 84000, descripcion: "Incluye camarones y palmitos x160 gr adicionales." },
    ],
  },
  {
    id: "fam6-especial",
    categoriaId: "familiar-6",
    nombre: "Especial",
    descripcion: "Arroz chino 2100 gr + camarones y palmitos x320 gr + pollo desmenuzado + carne picada + jamón + vegetales + papas x360 gr + 6 huevos de codorniz.",
    precio: 70000,
    imagen: img("especial.jpg"),
    activo: true,
  },
  {
    id: "fam6-alitas",
    categoriaId: "familiar-6",
    nombre: "Alitas con BBQ",
    descripcion: "12 alitas con BBQ + arroz chino 2100 gr + pollo desmenuzado + carne picada + jamón + vegetales + papas x360 gr + 6 huevos de codorniz.",
    precio: 70000,
    imagen: img("alitas-x4.jpg"),
    activo: true,
  },

  // ---------- PLATOS ESPECIALES ----------
  {
    id: "esp-chowsuey-sencillo",
    categoriaId: "especiales",
    nombre: "Chop Suey Sencillo",
    descripcion: "Verduras orientales + pollo desmenuzado + carne picada + papas x60 gr. Opcional con arroz.",
    precio: 22000,
    imagen: img("chop-suey.jpg"),
    activo: true,
    variantes: [
      { id: "solo", nombre: "Chow Suey Sencillo", precio: 22000 },
      { id: "camaron", nombre: "+ Adición de Camarón", precio: 28000 },
    ],
  },
  {
    id: "esp-chowsuey-duo",
    categoriaId: "especiales",
    nombre: "Chop Suey Duo",
    descripcion: "Verduras orientales + pollo desmenuzado + carne picada + papas x120 gr. Opcional con arroz.",
    precio: 29000,
    imagen: img("chop-suey.jpg"),
    activo: true,
    variantes: [
      { id: "solo", nombre: "Chow Suey Duo", precio: 29000 },
      { id: "camaron", nombre: "+ Adición de Camarón", precio: 33000 },
    ],
  },
  {
    id: "esp-chowmein",
    categoriaId: "especiales",
    nombre: "Chow Mein",
    descripcion: "Pasta oriental ramen + verduras orientales + pollo desmenuzado + carne picada + papas x60 gr.",
    precio: 21000,
    imagen: img("chow-mein.jpg"),
    activo: true,
    variantes: [
      { id: "solo", nombre: "Chow Mein", precio: 21000 },
      { id: "camaron", nombre: "+ Adición de Camarón", precio: 26000 },
    ],
  },
  {
    id: "esp-mazorcada",
    categoriaId: "especiales",
    nombre: "Mazorcada Oriental",
    descripcion: "Maíz tierno, verduras orientales, pollo desmenuzado, jamón, carne picada, queso y papa chip.",
    precio: 20000,
    imagen: img("mazorcada.jpg"),
    etiquetas: ["Nuevo"],
    activo: true,
  },
  {
    id: "esp-pollo-agridulce",
    categoriaId: "especiales",
    nombre: "Pollo Agridulce O.K.",
    descripcion: "Trozos de pechuga en tempura bañados en una exquisita salsa agridulce con piña + papas x60 gr.",
    precio: 20000,
    imagen: img("pollo-agridulce.jpg"),
    masVendido: true,
    activo: true,
    variantes: [
      { id: "solo", nombre: "Pollo Agridulce O.K.", precio: 20000 },
      { id: "arroz", nombre: "+ Adición de Arroz", precio: 24000 },
    ],
  },

  // ---------- A LA CARTA ----------
  {
    id: "carta-chuleta",
    categoriaId: "a-la-carta",
    nombre: "Chuleta de Cerdo",
    descripcion: "Porción de 240 gr + papa a la francesa x120 gr, acompañada de ensalada del día y salsa BBQ.",
    precio: 25000,
    imagen: img("chuleta.jpg"),
    activo: true,
  },
  {
    id: "carta-churrasco",
    categoriaId: "a-la-carta",
    nombre: "Churrasco",
    descripcion: "Porción de 240 gr + papa a la francesa x120 gr, acompañada de ensalada del día y chimichurri.",
    precio: 27000,
    imagen: img("churrasco.jpg"),
    destacado: true,
    activo: true,
  },
  {
    id: "carta-pechuga",
    categoriaId: "a-la-carta",
    nombre: "Pechuga a la Plancha",
    descripcion: "Porción de 200 gr + papa a la francesa x120 gr, acompañada de ensalada del día y salsa BBQ.",
    precio: 25000,
    imagen: img("pechuga-plancha.jpg"),
    activo: true,
  },
  {
    id: "carta-crema",
    categoriaId: "a-la-carta",
    nombre: "Crema de Pollo o Champiñón",
    descripcion: "Delicada y cremosa, acompañada de crujientes papas fosforito para el contraste perfecto.",
    precio: 7500,
    imagen: img("crema-pollo-champinon.jpg"),
    activo: true,
  },

  // ---------- COMIDA RÁPIDA ----------
  {
    id: "rapida-hamburguesa",
    categoriaId: "comida-rapida",
    nombre: "Hamburguesa",
    descripcion: "Carne de res 1/4 de libra + cebolla grilled con pollo desmenuzado + jamón + tomate + queso + huevo de codorniz + salsas + papas a la francesa x60 gr.",
    precio: 17000,
    imagen: img("hamburguesa.jpg"),
    masVendido: true,
    activo: true,
  },
  {
    id: "rapida-combo-amigos",
    categoriaId: "comida-rapida",
    nombre: "Combo Amigos",
    descripcion: "3 hamburguesas de res 1/4 de libra + cebolla grilled con pollo desmenuzado + jamón + tomate + queso + huevo de codorniz + salsas + 3 papas a la francesa x60 gr + 1 gaseosa 1.5L.",
    precio: 55000,
    imagen: img("combo-amigos.jpg"),
    etiquetas: ["Promoción"],
    activo: true,
  },
  {
    id: "rapida-combo-duo",
    categoriaId: "comida-rapida",
    nombre: "Combo Duo Hamburguesa",
    descripcion: "2 hamburguesas con carne de res 1/4 de libra, cebolla grilled con pollo desmenuzado, jamón, tomate, queso, huevos de codorniz, salsas, papas a la francesa x60 gr c/u y 2 gaseosas 250ml.",
    precio: 38000,
    imagen: img("combo-duo-hamburguesas.jpg"),
    etiquetas: ["Promoción"],
    activo: true,
  },
  {
    id: "rapida-perro",
    categoriaId: "comida-rapida",
    nombre: "Perro Caliente",
    descripcion: "Salchicha americana + cebolla grilled con pollo desmenuzado + queso + huevo de codorniz + papa chip + salsas.",
    precio: 14000,
    imagen: img("perro-caliente.jpg"),
    activo: true,
  },
  {
    id: "rapida-combo-perro",
    categoriaId: "comida-rapida",
    nombre: "Combo Perro",
    descripcion: "2 perros calientes con salchicha americana, cebolla grilled con pechuga desmenuzada, queso, huevo de codorniz, papa chip y salsas + 2 bebidas 250ml.",
    precio: 32000,
    imagen: img("combo-perro.jpg"),
    etiquetas: ["Promoción"],
    activo: true,
  },
  {
    id: "rapida-salchipapa",
    categoriaId: "comida-rapida",
    nombre: "Salchipapa",
    descripcion: "Papas a la francesa, salchicha americana, pollo desmenuzado, queso, huevo de codorniz y salsas.",
    precio: 17000,
    imagen: img("salchipapa.jpg"),
    activo: true,
  },

  // ---------- BEBIDAS ----------
  {
    id: "beb-postobon-15",
    categoriaId: "bebidas",
    nombre: "Gaseosa Postobón 1.5L",
    descripcion: "Botella familiar 1.5 litros. Sabor a elegir.",
    precio: 6500,
    imagen: img("bebidas/gaseosa-postobon-15.jpg"),
    activo: true,
    variantes: [
      { id: "normal", nombre: "Normal", precio: 6500 },
      { id: "ginger", nombre: "Ginger", precio: 7000 },
    ],
  },
  {
    id: "beb-postobon-250",
    categoriaId: "bebidas",
    nombre: "Gaseosa Postobón 250ml",
    descripcion: "Botella personal 250ml.",
    precio: 3000,
    imagen: img("bebidas/gaseosa-postobon-250.jpg"),
    activo: true,
  },
  {
    id: "beb-jugo-hit",
    categoriaId: "bebidas",
    nombre: "Jugo Hit 500ml",
    descripcion: "Botella personal 500ml.",
    precio: 4500,
    imagen: img("bebidas/jugo-hit.jpg"),
    activo: true,
  },
  {
    id: "beb-agua-cristal",
    categoriaId: "bebidas",
    nombre: "Agua Cristal 600ml",
    descripcion: "Agua sin gas, botella 600ml.",
    precio: 2400,
    imagen: img("bebidas/agua-cristal.jpg"),
    activo: true,
  },
  {
    id: "beb-agua-gas-cristal",
    categoriaId: "bebidas",
    nombre: "Agua con Gas Cristal 600ml",
    descripcion: "Agua con gas, botella 600ml.",
    precio: 2600,
    imagen: img("bebidas/agua-gas-cristal.jpg"),
    activo: true,
  },
  {
    id: "beb-cerveza-poker",
    categoriaId: "bebidas",
    nombre: "Cerveza Poker",
    descripcion: "Lata fría, para acompañar tu pedido.",
    precio: 4500,
    imagen: img("bebidas/cerveza-poker.jpg"),
    activo: true,
  },
  {
    id: "beb-cola-y-pola",
    categoriaId: "bebidas",
    nombre: "Cola y Pola",
    descripcion: "Lata fría, la combinación clásica.",
    precio: 3500,
    imagen: img("bebidas/cola-y-pola.jpg"),
    activo: true,
  },
];
